export const SET_MENU_STATE = 'SET_MENU_STATE';
export const SET_OVERLAY_STATE = 'SET_OVERLAY_STATE';
export const UPDATE_ANSWERS = 'UPDATE_ANSWERS';
export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE';