export const SET_MENU_STATE = 'SET_MENU_STATE';
export const SET_OVERLAY_STATE = 'SET_OVERLAY_STATE';
export const INIT_QUIZ_ITEMS = 'INIT_QUIZ_ITEMS';
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
export const SET_ITEM_RESPONSE = 'SET_ITEM_RESPONSE';
